security:
    encoders:
        Vorterix\BackendBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: VorterixBackendBundle:User }

    firewalls:
        login_firewall:
            pattern:   ^/backend/login$
            anonymous: ~
        backend_area:
            pattern:    ^/backend
            http_basic: ~
            security: true
            form_login:
                login_path: /backend/login
                check_path: /backend/login_check
                csrf_provider: form.csrf_provider
            logout:
                path:   /backend/logout
                target: /backend/login

    access_control:
        - { path: ^/backend/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend, roles: [ROLE_ADMIN, ROLE_USER] }