admin:
    path:     /hello/{name}
    defaults: { _controller: VorterixBackendBundle:Default:index }

VorterixBackendBundle_post:
    path:     backend/post/
    defaults: { _controller: VorterixBackendBundle:Post:index }

VorterixBackendBundle_post_new:
    path:     backend/post/new
    defaults: { _controller: VorterixBackendBundle:Post:new }

VorterixBackendBundle_post_save:
    path:     backend/post/save
    defaults: { _controller: VorterixBackendBundle:Post:save }

VorterixBackendBundle_post_edit:
    path:     backend/post/edit/{id}
    defaults: { _controller: VorterixBackendBundle:Post:edit, id : null }

VorterixBackendBundle_post_delete:
    path:     backend/post/delete/{id}
    defaults: { _controller: VorterixBackendBundle:Post:delete, id : null }
    
VorterixBackendBundle_category:
    path:     backend/category
    defaults: { _controller: VorterixBackendBundle:Category:index }

VorterixBackendBundle_category_new:
    path:     backend/category/new
    defaults: { _controller: VorterixBackendBundle:Category:new }

VorterixBackendBundle_category_save:
    path:     backend/category/save
    defaults: { _controller: VorterixBackendBundle:Category:save }

VorterixBackendBundle_category_edit:
    path:     backend/category/edit/{id}
    defaults: { _controller: VorterixBackendBundle:Category:edit, id : null }

VorterixBackendBundle_category_delete:
    path:     backend/category/delete/{id}
    defaults: { _controller: VorterixBackendBundle:Category:delete, id : null }
    
VorterixBackendBundle_category_list:
    path:     backend/category/list/{id}
    defaults: { _controller: VorterixBackendBundle:Category:list, id : null }
    
login:
    path:    backend/login
    defaults: { _controller: VorterixBackendBundle:Security:login }
    
login_check:
    path:    backend/login_check
    
VorterixBackendBundle_logout:
    path:   /backend/logout
    
VorterixBackendBundle_ajupload:
    pattern:  backend/ajupload
    defaults: { _controller: VorterixBackendBundle:Uploader:ajUpload }

VorterixBackendBundle_getFiles:
    pattern:  backend/getFiles
    defaults: { _controller: VorterixBackendBundle:Post:files }    

