index:
    path:     /backend
    defaults: { _controller: VorterixBackendBundle:Post:index }

VorterixBackendBundle_post:
    path:     backend/post
    defaults: { _controller: VorterixBackendBundle:Post:index }

VorterixBackendBundle_post_new:
    path:     backend/post/new
    defaults: { _controller: VorterixBackendBundle:Post:new }

VorterixBackendBundle_post_save:
    path:     backend/post/save
    defaults: { _controller: VorterixBackendBundle:Post:save }
    
VorterixBackendBundle_removeCover:
    path:     backend/post/removeCover
    defaults: { _controller: VorterixBackendBundle:Post:removeCover }

VorterixBackendBundle_post_edit:
    path:     backend/post/edit/{id}
    defaults: { _controller: VorterixBackendBundle:Post:edit, id : null }

VorterixBackendBundle_post_delete:
    path:     backend/post/delete/{id}
    defaults: { _controller: VorterixBackendBundle:Post:delete, id : null }
    
VorterixBackendBundle_category:
    path:     backend/category
    defaults: { _controller: VorterixBackendBundle:Category:index }

VorterixBackendBundle_category_new:
    path:     backend/category/new
    defaults: { _controller: VorterixBackendBundle:Category:new }

VorterixBackendBundle_category_save:
    path:     backend/category/save
    defaults: { _controller: VorterixBackendBundle:Category:save }

VorterixBackendBundle_category_edit:
    path:     backend/category/edit/{id}
    defaults: { _controller: VorterixBackendBundle:Category:edit, id : null }

VorterixBackendBundle_category_delete:
    path:     backend/category/delete/{id}
    defaults: { _controller: VorterixBackendBundle:Category:delete, id : null }
    
VorterixBackendBundle_category_list:
    path:     backend/category/list/{id}
    defaults: { _controller: VorterixBackendBundle:Category:list, id : null }
    
VorterixBackendBundle_ajupload:
    pattern:  /backend/ajupload
    defaults: { _controller: VorterixBackendBundle:Uploader:ajUpload }
    
VorterixBackendBundle_removeImage:
    pattern:  /backend/removeImage
    defaults: { _controller: VorterixBackendBundle:Uploader:removeImage }

VorterixBackendBundle_FileTree:
    pattern:  /backend/fileTree
    defaults: { _controller: VorterixBackendBundle:Uploader:fileTree }

VorterixBackendBundle_cropImage:
    pattern:  /backend/cropImage
    defaults: { _controller: VorterixBackendBundle:Uploader:cropImage }    

VorterixBackendBundle_gallery:
    pattern:  /backend/gallery
    defaults: { _controller: VorterixBackendBundle:Gallery:index }

VorterixBackendBundle_gallery_new:
    pattern:  /backend/gallery/new
    defaults: { _controller: VorterixBackendBundle:Gallery:new }
    
VorterixBackendBundle_gallery_save:
    pattern:  /backend/gallery/save
    defaults: { _controller: VorterixBackendBundle:Gallery:save }
    
VorterixBackendBundle_gallery_edit:
    pattern:  /backend/gallery/edit/{id}
    defaults: { _controller: VorterixBackendBundle:Gallery:edit, id: null }
    
VorterixBackendBundle_gallery_delete:
    pattern:  /backend/gallery/delete/{id}
    defaults: { _controller: VorterixBackendBundle:Gallery:delete, id: null }
    
VorterixBackendBundle_Json:
    pattern:  /backend/Json
    defaults: { _controller: VorterixBackendBundle:Json:index }
    
VorterixBackendBundle_Json_generate:
    pattern:  /backend/Json/generateJson/{id}
    defaults: { _controller: VorterixBackendBundle:Json:generate, id: null }
    
VorterixBackendBundle_removeImageGallery:
    pattern:  /backend/removeImageGallery
    defaults: { _controller: VorterixBackendBundle:Image:removeImage }

 
VorterixBackendBundle_section:
    path:     backend/section
    defaults: { _controller: VorterixBackendBundle:Section:index }

VorterixBackendBundle_section_new:
    path:     backend/section/new
    defaults: { _controller: VorterixBackendBundle:Section:new }

VorterixBackendBundle_section_save:
    path:     backend/section/save
    defaults: { _controller: VorterixBackendBundle:Section:save }

VorterixBackendBundle_section_edit:
    path:     backend/section/edit/{id}
    defaults: { _controller: VorterixBackendBundle:Section:edit, id : null }

VorterixBackendBundle_section_delete:
    path:     backend/section/delete/{id}
    defaults: { _controller: VorterixBackendBundle:Section:delete, id : null }
    
VorterixBackendBundle_section_list:
    path:     backend/section/list/{id}
    defaults: { _controller: VorterixBackendBundle:Section:list, id : null }
    
VorterixBackendBundle_section_removeImage:
    path:     backend/section/removeImage
    defaults: { _controller: VorterixBackendBundle:Section:removeImage }
    
VorterixBackendBundle_section_saveImage:
    path:     backend/section/saveImage
    defaults: { _controller: VorterixBackendBundle:Section:saveImage }
    